//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia_de_Turismo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquete
    {
        public Paquete()
        {
            this.Reservas = new HashSet<Reserva>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Foto { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public bool Destacado { get; set; }
        public Nullable<int> LugaresDisponibles { get; set; }
        public int PrecioPorPersona { get; set; }
    
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
